### ISSUE TITLE
Add ECONNRESET to responses from Velocify?

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-velocify#44] opened 2015-07-22 14:52 UTC
I recently received an error from Velocify:

https://next.leadconduit.com/events/55aedbc33af2877d45ffd890?event_id=55aedbc43af2877d45ffd89e

Should ECONNRESET be considered a failure or an error?

**Comment by alexkwolfe** [comment] 2015-07-22 14:55
This is an error. Basically what happened is that we started talking to Velocify's server, but their server decided midway through that "conversation" that it wasn't interested in talking anymore.

**Comment by kcaponeAP** [comment] 2015-07-24 17:28
Closing, as I think I found the cause of the issue.

**Comment by kcaponeAP** [comment] 2015-09-11 14:59
The Velocify integration is giving this error when Velocify's servers take over 10 seconds to respond. This happens occasionally and negatively impacts the customer because we close the connection. Can anything be done here to keep the connection open longer?

I just sent a lead manually through my rest client and it took 11491ms to get a response.

Lead that failed:
https://next.leadconduit.com/events/55f27aca4a817f733013393c?event_id=55f27acc4a817f733013394f

Do not try to repost as it won't work / it will dupe out on the Velocify side.

**Comment by alexkwolfe** [comment] 2015-09-11 15:58
We don't time out on our end at 10 seconds. The velocity integration uses the same mechanism as other integrations to send a lead. If we were the cause of this, I'd think that other integrations would be impacted too. bit we can do some additional investigating.

**Comment by cgrayson** [comment] 2015-09-11 17:22
Where did that "10 second" number come from? These are indeed timing out, but at 127s, not 10s: 

![screen shot 2015-09-11 at 12 15 19 pm](https://cloud.githubusercontent.com/assets/5596/9821280/f3c5e46c-587e-11e5-8a20-e1af18161b38.png)

Looking through logs, I found that in addition to that one failed lead in that account, there were 7 other timeouts this morning in another account: https://next.leadconduit.com/events?recipient_id=5428718179ea6abc8464e65b&flow_id=53c997339d29c9787d00006b&type=recipient&outcome=error&start=2015-09-01&end=2015-09-11

**Comment by kcaponeAP** [comment] 2015-09-11 17:29
The figure came from how long it took me to successfully send the lead through my REST client. I can't have customers not getting leads because the integration doesn't send it, so i scooped it from LCN ASAP and sent it onto the client and experienced a delay outside of the platform.

**Comment by cgrayson** [comment] 2015-09-11 17:36
I see. The more relevant time in a case like this is the duration spent on the lead when it failed. 

And since it did succeed when you manually posted it (though still slower than the typical 1-2s I'm seeing for successes right now), we can figure it wasn't something related to that lead's data. I.e., that's further evidence that the Velocify servers were at fault.

**Comment by kcaponeAP** [comment] 2015-09-11 17:39
absolutely. i do have a support ticket into them. but what is confusing for me is that in the velocify step of the lead i cited, there is no response from the server. so if there is no response from the server, is it our integration that provides that error? 

is there any way we can wait longer for a response? is that even something we should do?

furthermore, if its an error, in the future, how can the system be improved upon when we have a situation like this. 'retry after error' or something to that effect.

**Comment by cgrayson** [comment] 2015-09-11 17:54
Well, one can always wait longer, but on the other hand, there can still always be timeouts. If LC were to wait for 3 minutes instead of 2, then a recipient server might still not respond for 3.5. Meanwhile, that whole time, LC server and network resources are tied up. Add enough volume of leads, all stuck waiting for that long because a high-traffic recipient's servers are failing, and LC really starts struggling to handle everyone else's leads.

Also, remember that most of the posts to Velocify take less than 2 _seconds_. If a post still hasn't gotten a response for _60 times_ longer than that, then chances are something has gone badly anyway.

And yes, I think you're right that an automatic retry is probably the best solution to a case like this.

**Comment by kcaponeAP** [comment] 2015-09-11 17:56
100% with you on all of these points. From here, should we loop in Jones for a auto retry option? @alexj

**Comment by cgrayson** [comment] 2015-09-11 18:12
Sure. @alexj, consider yourself looped. Since that's an app-level feature, not specific to this integration, I'll close this issue. :smiley_cat:

**Closed by cgrayson** 2015-09-11 18:12 UTC
Labels: enhancement

**Comment by alexkwolfe** [comment] 2015-09-11 22:40
Please see my original response to this issue. Their service is closing the connection prematurely. That's what ECONNRESET means. 

The problem with retrying in this case is that we don't know the state of this lead in their database. Did it make it in? If so, the retry may dupe out. Did it not make it in? Then we should resend it. Problem is we don't know what to do because their service terminated the connection without responding. 

This is something they need to fix on their end. If this is a continuing problem, I would recommend sending leads that didn't make it Velocify to Barchrobot for manual reconciliation by a human.

**Comment by kcaponeAP** [comment] 2015-09-16 16:35
From the dev team @ Velocify: 

"We heard back from our developers. They stated that if a client has our duplicate management feature in Velocify, then it can slow down the import process if their database is checking for a lot of duplicates."

Which is in fact the case.

**Comment by alexkwolfe** [comment] 2015-09-16 16:59
When they say "import process" and "checking for a lot of duplicates" I immediately think they're referring to some sort of bulk or batch import. 

Regardless, the problem isn't necessarily one of slowness. It's that their system is dropping the connection. In fact, their server dropped the connection on the original lead referenced after only 11s. 

See https://next.leadconduit.com/events/55aedbc33af2877d45ffd890?event_id=55aedbc43af2877d45ffd89e
